version: '3.8'

services:
  web:
    build: .
    container_name: asistencia_facial-web
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

    volumes:
      - tunnel_data:/tunnel_data
    networks:
      - app_net
    depends_on:
      - nginx


  cf_tunnel:
    build:
      context: .
      dockerfile: Dockerfile.cf_tunnel
    container_name: cf_tunnel
    command: ["/bin/sh", "/app/scripts/cloudflared-entry.sh"]
    volumes:
      - tunnel_data:/tunnel_data
    networks:
      - app_net
    depends_on:
      - web

  nginx:
    image: nginx:latest
    container_name: asistencia_facial-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app_net

volumes:
  tunnel_data:

networks:
  app_net:
    driver: bridge
