# Generated by Django 5.1.7 on 2025-03-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('encoding', models.BinaryField()),
                ('salt', models.BinaryField()),
                ('registrado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
