# nginx.conf (versión base con HTTPS local usando certificados autofirmados)

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/dev.crt;
    ssl_certificate_key /etc/nginx/certs/dev.key;

    location / {
        proxy_pass http://web:8000;
    }
}


server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}
